import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatPrice(amount: number, lang: "en" | "ar" = "en") {
  const formatted = new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en-US", { maximumFractionDigits: 0 }).format(amount);
  return `$${formatted}`;
}

export const translations = {
  en: {
    brand: "Tripful",
    tagline: "Book your perfect stay",
    hero_title: "Your Journey Across the Middle East Begins Here",
    hero_subtitle: "From the golden dunes of Dubai to the holy sites of Makkah, from the Mediterranean shores of Tripoli to the ancient ruins of Petra — discover the region's finest hotels and travel bundles.",
    search_placeholder: "Where are you going?",
    search_btn: "Search",
    check_in: "Check-in",
    check_out: "Check-out",
    guests: "Guests",
    hotels: "Hotels",
    bundles: "Travel Bundles",
    per_night: "/ night",
    per_person: "/ person",
    available: "Available",
    sold_out: "Sold Out",
    book_now: "Book Now",
    view_details: "View Details",
    amenities: "Amenities",
    rooms: "Rooms",
    room_type: "Room Type",
    included: "What's Included",
    duration: "Duration",
    destinations: "Destinations",
    difficulty: "Difficulty",
    group_size: "Group Size",
    reviews: "Reviews",
    guest_name: "Full Name",
    email: "Email",
    phone: "Phone",
    special_requests: "Special Requests",
    confirm_booking: "Confirm Booking",
    booking_confirmed: "Booking Confirmed!",
    booking_confirmed_desc: "We'll send you a confirmation email shortly.",
    back_home: "Back to Home",
    featured_hotels: "Featured Hotels",
    featured_bundles: "Popular Travel Bundles",
    explore: "Explore",
    nights: "nights",
    days: "days",
    login: "Login",
    register: "Sign Up",
    logout: "Logout",
    my_bookings: "My Bookings",
    footer_about: "About Tripful",
    footer_about_desc: "Your trusted partner for unforgettable travel experiences across the Middle East and beyond.",
    footer_links: "Quick Links",
    footer_contact: "Contact",
    footer_rights: "© 2026 Tripful. All rights reserved.",
    why_choose: "Why Choose Tripful",
    stats_hotels: "Luxury Hotels",
    stats_bundles: "Travel Bundles",
    stats_countries: "Countries",
    stats_guests: "Happy Guests",
    filter_price: "Price Range",
    filter_amenities: "Amenities",
    filter_stars: "Star Rating",
    filter_country: "Country",
    filter_property: "Property Type",
    clear_filters: "Clear All",
    results_found: "properties found",
    sort_by: "Sort by",
    sort_recommended: "Recommended",
    sort_price_low: "Price: Low to High",
    sort_price_high: "Price: High to Low",
    sort_rating: "Top Rated",
    no_results: "No properties match your search",
    testimonials: "What Our Guests Say",
    newsletter: "Get Exclusive Deals",
    newsletter_desc: "Subscribe for the best hotel and travel bundle offers",
    subscribe: "Subscribe",
    email_placeholder: "Your email address",
    per_night_short: "night",
  },
  ar: {
    brand: "تريبفول",
    tagline: "احجز إقامتك المثالية",
    hero_title: "رحلتك عبر الشرق الأوسط تبدأ من هنا",
    hero_subtitle: "من كثبان دبي الذهبية إلى الأماكن المقدة في مكة، من شواطئ البحر المتوسط في طرابلس إلى آثار البتراء — اكتشف أفضل الفنادق وباقات السفر في المنطقة.",
    search_placeholder: "إلى أين تذهب؟",
    search_btn: "بحث",
    check_in: "تاريخ الوصول",
    check_out: "تاريخ المغادرة",
    guests: "الضيوف",
    hotels: "الفنادق",
    bundles: "باقات السفر",
    per_night: "/ ليلة",
    per_person: "/ شخص",
    available: "متاح",
    sold_out: "نفدت",
    book_now: "احجز الآن",
    view_details: "عرض التفاصيل",
    amenities: "المرافق",
    rooms: "الغرف",
    room_type: "نوع الغرفة",
    included: "المشمول",
    duration: "المدة",
    destinations: "الوجهات",
    difficulty: "المستوى",
    group_size: "حجم المجموعة",
    reviews: "التقييمات",
    guest_name: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    special_requests: "طلبات خاصة",
    confirm_booking: "تأكيد الحجز",
    booking_confirmed: "تم تأكيد الحجز!",
    booking_confirmed_desc: "سنرسل لك رسالة تأكيد قريبًا.",
    back_home: "العودة للرئيسية",
    featured_hotels: "فنادق مميزة",
    featured_bundles: "باقات سفر رائجة",
    explore: "استكشف",
    nights: "ليالٍ",
    days: "أيام",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    my_bookings: "حجوزاتي",
    footer_about: "عن تريبفول",
    footer_about_desc: "شريكك الموثوق لتجارب سفر لا تُنسى عبر الشرق الأوسط وما وراءه.",
    footer_links: "روابط سريعة",
    footer_contact: "تواصل معنا",
    footer_rights: "© 2026 تريبفول. جميع الحقوق محفوظة.",
    why_choose: "لماذا تختار تريبفول",
    stats_hotels: "فنادق فاخرة",
    stats_bundles: "باقات سفر",
    stats_countries: "دول",
    stats_guests: "ضيف سعيد",
    filter_price: "نطاق السعر",
    filter_amenities: "المرافق",
    filter_stars: "التقييم بالنجوم",
    filter_country: "الدولة",
    filter_property: "نوع العقار",
    clear_filters: "مسح الكل",
    results_found: "نتيجة",
    sort_by: "ترتيب حسب",
    sort_recommended: "موصى به",
    sort_price_low: "السعر: الأقل",
    sort_price_high: "السعر: الأعلى",
    sort_rating: "الأعلى تقييمًا",
    no_results: "لا توجد نتائج مطابقة",
    testimonials: "ماذا يقول ضيوفنا",
    newsletter: "احصل على عروض حصرية",
    newsletter_desc: "اشترك للحصول على أفضل عروض الفنادق وباقات السفر",
    subscribe: "اشترك",
    email_placeholder: "بريدك الإلكتروني",
    per_night_short: "ليلة",
  },
};

export type Lang = "en" | "ar";
export type Dict = typeof translations.en;

export function t(lang: Lang, key: keyof Dict): string {
  return translations[lang][key] ?? key;
}
