import { type ClassValue, clsx } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export function formatPrice(amount: number, lang: "en" | "ar" = "en") {
  const formatted = new Intl.NumberFormat(lang === "ar" ? "ar-SA" : "en-US", { maximumFractionDigits: 0 }).format(amount);
  return lang === "ar" ? `${formatted} ر.س` : `$${formatted}`;
}

export const translations = {
  en: {
    brand: "Tripful",
    tagline: "Book your perfect stay",
    search_placeholder: "Where are you going?",
    search_btn: "Search",
    check_in: "Check-in",
    check_out: "Check-out",
    guests: "Guests",
    hotels: "Hotels",
    bundles: "Travel Bundles",
    per_night: "/ night",
    per_person: "/ person",
    available: "Available",
    sold_out: "Sold Out",
    book_now: "Book Now",
    view_details: "View Details",
    amenities: "Amenities",
    rooms: "Rooms",
    included: "What's Included",
    duration: "Duration",
    destinations: "Destinations",
    difficulty: "Difficulty",
    group_size: "Group Size",
    reviews: "Reviews",
    guest_name: "Full Name",
    email: "Email",
    phone: "Phone",
    special_requests: "Special Requests",
    confirm_booking: "Confirm Booking",
    booking_confirmed: "Booking Confirmed!",
    booking_confirmed_desc: "We'll send you a confirmation email shortly.",
    back_home: "Back to Home",
    featured_hotels: "Featured Hotels",
    featured_bundles: "Popular Travel Bundles",
    explore: "Explore",
    nights: "nights",
    days: "days",
    login: "Login",
    register: "Sign Up",
    logout: "Logout",
    my_bookings: "My Bookings",
    footer_about: "About Tripful",
    footer_about_desc: "Your trusted partner for unforgettable travel experiences.",
    footer_links: "Quick Links",
    footer_contact: "Contact",
    footer_rights: "© 2026 Tripful. All rights reserved.",
    // Home page translations
    why_choose: "Why Choose Tripful",
    testimonials: "What Our Guests Say",
    stats_hotels: "Hotels",
    stats_bundles: "Travel Bundles",
    stats_countries: "Countries",
    stats_guests: "Happy Guests",
    // New keys
    profile: "Profile",
    deals: "Deals & Discounts",
    trending: "Trending Places",
    overview: "Overview",
    upcoming_bookings: "Upcoming Bookings",
    past_bookings: "Past Bookings",
    cancelled_bookings: "Cancelled",
    total_bookings: "Total Bookings",
    total_spent: "Total Spent",
    loyalty_points: "Loyalty Points",
    member_since: "Member since",
    account_settings: "Account Settings",
    full_name: "Full Name",
    email_address: "Email Address",
    phone_number: "Phone Number",
    country: "Country",
    city: "City",
    save_changes: "Save Changes",
    no_bookings_yet: "No bookings yet",
    no_bookings_desc: "Start exploring and book your first stay",
    browse_hotels: "Browse Hotels",
    booking_id: "Booking ID",
    check_in_date: "Check-in",
    check_out_date: "Check-out",
    status: "Status",
    amount: "Amount",
    actions: "Actions",
    view_receipt: "View Receipt",
    cancel_booking: "Cancel",
    confirmed: "Confirmed",
    pending: "Pending",
    completed: "Completed",
    cancelled: "Cancelled",
    limited_time_offers: "Limited-Time Offers",
    deals_subtitle: "Save big on premium stays and bundles",
    off: "OFF",
    trending_destinations: "Trending Destinations",
    trending_subtitle: "Most booked places this season",
    bookings_count: "bookings",
    explore_deals: "Explore Deals",
    view_all_deals: "View All Deals",
    popular_now: "Popular Now",
    ends_in: "Ends in",
    days_left: "days left",
    hours_left: "hours left",
    redeem_deal: "Redeem Deal",
    copy_code: "Copy Code",
    code_copied: "Code Copied!",
    no_deals_available: "No deals available right now",
    check_back_soon: "Check back soon for new offers",
    guest_user: "Guest User",
    sign_in_for_bookings: "Sign in to sync your bookings across devices",
  },
  ar: {
    brand: "تريبفول",
    tagline: "احجز إقامتك المثالية",
    search_placeholder: "إلى أين تذهب؟",
    search_btn: "بحث",
    check_in: "تاريخ الوصول",
    check_out: "تاريخ المغادرة",
    guests: "الضيوف",
    hotels: "الفنادق",
    bundles: "باقات السفر",
    per_night: "/ ليلة",
    per_person: "/ شخص",
    available: "متاح",
    sold_out: "نفدت",
    book_now: "احجز الآن",
    view_details: "عرض التفاصيل",
    amenities: "المرافق",
    rooms: "الغرف",
    included: "المشمول",
    duration: "المدة",
    destinations: "الوجهات",
    difficulty: "المستوى",
    group_size: "حجم المجموعة",
    reviews: "التقييمات",
    guest_name: "الاسم الكامل",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    special_requests: "طلبات خاصة",
    confirm_booking: "تأكيد الحجز",
    booking_confirmed: "تم تأكيد الحجز!",
    booking_confirmed_desc: "سنرسل لك رسالة تأكيد قريبًا.",
    back_home: "العودة للرئيسية",
    featured_hotels: "فنادق مميزة",
    featured_bundles: "باقات سفر رائجة",
    explore: "استكشف",
    nights: "ليالٍ",
    days: "أيام",
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    my_bookings: "حجوزاتي",
    footer_about: "عن تريبفول",
    footer_about_desc: "شريكك الموثوق لتجارب سفر لا تُنسى.",
    footer_links: "روابط سريعة",
    footer_contact: "تواصل معنا",
    footer_rights: "© 2026 تريبفول. جميع الحقوق محفوظة.",
    // Home page translations
    why_choose: "لماذا تريبفول",
    testimonials: "آراء ضيوفنا",
    stats_hotels: "فنادق",
    stats_bundles: "باقات سفر",
    stats_countries: "دول",
    stats_guests: "ضيوف سعداء",
    // New keys
    profile: "الملف الشخصي",
    deals: "العروض والخصومات",
    trending: "الأماكن الرائجة",
    overview: "نظرة عامة",
    upcoming_bookings: "الحجوزات القادمة",
    past_bookings: "الحجوزات السابقة",
    cancelled_bookings: "ملغاة",
    total_bookings: "إجمالي الحجوزات",
    total_spent: "إجمالي الإنفاق",
    loyalty_points: "نقاط الولاء",
    member_since: "عضو منذ",
    account_settings: "إعدادات الحساب",
    full_name: "الاسم الكامل",
    email_address: "البريد الإلكتروني",
    phone_number: "رقم الهاتف",
    country: "الدولة",
    city: "المدينة",
    save_changes: "حفظ التغييرات",
    no_bookings_yet: "لا توجد حجوزات بعد",
    no_bookings_desc: "ابدأ الاستكشاف واحجز أول إقامة لك",
    browse_hotels: "تصفح الفنادق",
    booking_id: "رقم الحجز",
    check_in_date: "تاريخ الوصول",
    check_out_date: "تاريخ المغادرة",
    status: "الحالة",
    amount: "المبلغ",
    actions: "إجراءات",
    view_receipt: "عرض الإيصال",
    cancel_booking: "إلغاء",
    confirmed: "مؤكد",
    pending: "قيد الانتظار",
    completed: "مكتمل",
    cancelled: "ملغى",
    limited_time_offers: "عروض لفترة محدودة",
    deals_subtitle: "وفّر أكثر على الفنادق والباقات الفاخرة",
    off: "خصم",
    trending_destinations: "الوجهات الرائجة",
    trending_subtitle: "الأماكن الأكثر حجزًا هذا الموسم",
    bookings_count: "حجز",
    explore_deals: "استكشف العروض",
    view_all_deals: "عرض كل العروض",
    popular_now: "رائج الآن",
    ends_in: "ينتهي خلال",
    days_left: "أيام متبقية",
    hours_left: "ساعات متبقية",
    redeem_deal: "استخدم العرض",
    copy_code: "نسخ الكود",
    code_copied: "تم نسخ الكود!",
    no_deals_available: "لا توجد عروض حاليًا",
    check_back_soon: "تحقق قريبًا من العروض الجديدة",
    guest_user: "ضيف",
    sign_in_for_bookings: "سجّل الدخول لمزامنة حجوزاتك عبر الأجهزة",
  },
};

export type Lang = "en" | "ar";
export type Dict = typeof translations.en;

export function t(lang: Lang, key: keyof Dict): string {
  return translations[lang][key] ?? key;
}
